id: '1740512740108'
alias: Announce sunrise
description: ''
triggers:
- trigger: sun
  event: sunrise
  offset: 0
conditions: []
actions:
- action: assist_satellite.announce
  metadata: {}
  data:
    message: De zon is nu helemaal op!
mode: single
